config/routes.rb
Rails.application.routes.draw do
   root to: "toppages#index"
   get "settings", to: "settings#index"
   get "signup", to: "users#new"
   get "login", to: "sessions#new"
   post "log", to: "sessions#create"
   delete "logout", to: "sessions#destroy"
   delete "sakuzyo", to: "topics#destroy"
   resources "myshines" 
   resources "users"
   get "ranking", to: "users#ranking"
   resources "topics"
   resources "chats"
   resources "coments"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :coments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 50 } 
end

app/models/coment.rb
class Coment < ApplicationRecord
  belongs_to :user
  belongs_to :chat
  validates :content, presence: true, length: { maximum: 150 }
end

app/models/myshine.rb
class Myshine < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :myshines, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: { maximum: 50 }
  
end

app/models/user.rb
class User < ApplicationRecord
 
  
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
  uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :myshines, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :coments, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :coments, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chat = Chat.new
    @chats = Chat.all.uniq
  end
  def show
    @chat = Chat.find(params[:id])
    @coment = current_user.coments.new(chat_id: @chat.id)
    @coments = Coment.where(chat_id: @chat.id).order("updated_at DESC").page(params[:page])
  end
  def create
    @chat = current_user.chats.new(chat_params)
    if @chat.save
      flash[:success] = "投稿しました"
      redirect_to chats_path
    else
      flash.now[:danger] = "投稿できません"
      @chats = Chat.all.uniq
      render "chats/index"
    end
  end
  def destroy
    @chat = Chat.find(params[:id])
    @chat.destroy
    flash[:success] = "投稿を削除しました"
    redirect_back(fallback_location: root_path)
  end
  private
  def chat_params
    params.require(:chat).permit(:title)
  end
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController
  def create
    @coment = current_user.coments.new(coment_params)
    @chat = @coment.chat
    if @coment.save
      flash[:success] = "投稿しました"
      redirect_to chat_path(@chat)
    else
      flash.now[:danger] = "投稿できませんでした"
      @coments = Coment.where(chat_id: @chat.id).order("updated_at DESC").page(params[:page])
      render "chats/show"
    end
  end
  def destroy
    @coment = Coment.find(params[:id])
    @coment.destroy
    flash[:success] = "コメントを削除しました"
    redirect_back(fallback_location: root_path)
  end
  private
  def coment_params
    params.require(:coment).permit(:content, :chat_id)
  end
end

app/controllers/myshines_controller.rb
class MyshinesController < ApplicationController
  def index
  end
  def new
    @topic = Topic.find(params[:topic_id])
    @myshine = current_user.myshines.build(topic_id: @topic.id)
  end
  def create
    @myshine = current_user.myshines.new(shine_params)
    @topic = @myshine.topic
    if @myshine.save
      flash[:success] = "投稿しました"
      redirect_to topic_path(@topic, user_id: current_user.id)
    else 
      flash.now[:danger] = "投稿できませんでした"
      render "myshines/new"
    end
  end
  def destroy
    @myshine = Myshine.find(params[:id])
    @myshine.destroy
    flash[:success] = "投稿を削除しました"
    redirect_back(fallback_location: root_path)
  end
  private
  def shine_params
    params.require(:myshine).permit(:image, :topic_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = "ログインしました"
      redirect_to root_url
    else 
      flash.now[:danger] = "ログインできませんでした"
      render :new
    end
  end
  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました　"
    redirect_to root_url
  end
  private
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else 
      return false
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def show
    @user = User.find(params[:user_id])
    @topic = Topic.find_by(id: params[:id])
    @myshines = @user.myshines.where(topic_id: @topic.id).order("created_at DESC").page(params[:page]).per(12)
    @topics = @user.topics.uniq
  end
  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      flash[:success] = "ワードを保存しました"
      redirect_to current_user
    else 
      flash.now[:danger] = "ワードを保存できませんでした"
      @user = current_user
      @topics = @user.topics.uniq - [@topic]
      render "users/show"
    end
  end
  def destroy
    @topic = current_user.topics.find_by(id: params[:id])
    @topic.destroy
    flash[:success] = "削除しました"
    redirect_back(fallback_location: root_path)
  end
  private
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
   
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    @users = User.where(private: false).order("updated_at DESC").page(params[:page]).per(12)
  end
  def ranking 
     @users = User.all.order("pv DESC").first(10)
  end
  def show
    unless current_user == @user
      unless @user.pv.present?
        @user.pv = 0
      end
      @user.pv = @user.pv + 1
      @user.save
    end
    @topics = @user.topics.uniq
    @topic = Topic.new
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザ登録しました"
      redirect_to root_url
    else
      flash.now[:danger] = "ユーザ登録できませんでした"
      render :new
    end
  end
  def edit
  end
  def update
    if @user.update(user_params)
      flash[:success] = "ユーザの情報を変更しました"
      redirect_to root_url
    else
      flash.now[:danger] = "ユーザの情報を変更できませんでした"
      render :edit
    end
  end
  def destroy
    @user.destroy
    flash[:success] = "ユーザを削除しました"
    redirect_to root_url
  end
  private 
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :private)
  end
  def correct_user
    @user = current_user
    unless @user
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end        
    def logged_in?
        !!current_user
    end
        
end

app/views/chats/index.html.erb
<div class="body_cover">
  <div class="chat">
    <h1 class="pc">掲示板</h1>
    <h3 class="sp">掲示板</h3>
    <div class="chat_new">
      <%= form_for(@chat) do |f| %>
      <%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力" %>
      <%= f.submit "作成", class: "btn btn-warning" %>
      <% end %>
    </div>
    <div class="coment_index">
      <h1 class="pc">タイトル一覧</h1>
      <h4 class="sp">タイトル一覧</h4>
      <% @chats.each do |chat| %>
        <h3><%= chat.id %> : <%= link_to chat.title, chat_path(chat) %>
            <%= link_to chat, method: :delete do %>
            <span class="glyphicon glyphicon-trash"></span>
            <% end %>
        </h3>
      <% end %>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<div class="body_cover">
  <div class="chat">
    <h1 class="pc"><%= @chat.title %>の掲示板</h1>
    <h3 class="sp"><%= @chat.title %>の<br>掲示板</h3>
    <%= link_to "戻る", chats_path, class: "btn btn-warning" %>
    <div class="coment_new">
      <%= form_for(@coment) do |f| %>
      <%= f.text_field :content, class: "form-control", placeholder: "コメント" %>
      <%= f.hidden_field :chat_id %>
      <%= f.submit "投稿", class: "btn btn-warning" %>
      <% end %>
    </div>
    <div class="coment_index">
      <% @coments.each do |coment| %>
        <h4><%= coment.id %>:<%= link_to coment.user.name, user_path(coment.user_id) %><%= coment.content %></h4>
        <h6><%= coment.created_at.strftime("%Y年 %m月 %d日") %></h6>
        <%= link_to coment, method: :delete do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_manner.html.erb
<ul>
  <li>
    <h3>1</h3>
    <p>左上にあるshineというボタンを押すことで、トップページに移動することができます。</p>
  </li>
  <li>
    <h3>2</h3>
    <p>自分のページはmyshineから入ることができます。画像を投稿したい場合は、
  先にタイトル投稿し、タイトルをクリックしてタイトル画面に移動してから、画像を投稿することができます。</p>
  </li>
  <li>
    <h3>3</h3>
    <p>othershineでは、アカウントを公開設定にしているユーザを表示しています。</p>
  </li>
  <li>
    <h3>4</h3>
    <p>掲示板では好きな(タイトルを作成して頂くこともできます。)タイトルをクリックし、そのページでコメントを入力することができます。
        多くの交流を楽しんでください。</p>
  </li>
  <li>
    <h3>5</h3>
    <p>ランキングでは、公開設定にしているユーザの中で、より多く閲覧されているユーザをランキング形式で表示しています。</p>
  </li>
   <li>
    <h3>6</h3>
    <p>ユーザ詳細からいつでも公開・非公開設定が行えます。</p>
  </li>
</ul>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <% if logged_in? %>
    <ul class="nav navbar-nav navbar-left">
      <li><h3><%= link_to "shine", root_path %></h3></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <%= link_to settings_path, remote: true do %>
      <span class="sp glyphicon glyphicon-th-list"></span>
       <% end %>
      <!-- モーダル・ダイアログ -->
      <div class="modal fade" id="sampleModal" tabindex="-1">
        	<div class="modal-dialog">
        		<div class="modal-content">
        			<div class="modal-header">
        				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
        				<h4 class="modal-title">使い方について</h4>
        			</div>
        			<div class="modal-body">
        				<%= render 'layouts/manner' %>
        			</div>
        			<div class="modal-footer">
        				<button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
        		  </div>
        	  </div>
          </div>
      </div>
    </ul>
    <div class="sp box">
      <li><div class="rule"><h4>使い方</h4></div></li>
       <li><h4><%= link_to "ユーザ詳細", edit_user_path(current_user) %></h4></li>
       <li><h4><%= link_to "ログアウト", logout_path, method: :delete %></h4></li>
      <li><h4><a href="https://docs.google.com/forms/d/e/1FAIpQLSfBomBCpxTeQ-pIOlRCxRpCyJuGS9VUoYV6h-GfwTaf8V_IPw/viewform?usp=pp_url">お問い合わせ</a></h4></li>
     </div>
     <div class="pc navbar_guide">
        <li><div class="rule"><p>使い方</p></div></li>
        <li><p><%= link_to "ユーザ詳細", edit_user_path(current_user) %></p></li>
        <li><p><%= link_to "ログアウト", logout_path, method: :delete %></p></li>
        <li><p><a href="https://docs.google.com/forms/d/e/1FAIpQLSfBomBCpxTeQ-pIOlRCxRpCyJuGS9VUoYV6h-GfwTaf8V_IPw/viewform?usp=pp_url">お問い合わせ</a></p></li>
     </div>
  <% else %>
    <ul class="nav navbar-nav navbar-left">
      <li><h3><%= link_to "shine", root_path %></h3></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <%= link_to settings_path, remote: true do %>
        <span class="sp glyphicon glyphicon-th-list"></span>
      <% end %>
    </ul>
    <div class="sp box">
      <li><div class="rule"><h4>使い方</h4></div></li>
      <li><h4><%= link_to "新規登録", signup_path %></h4></li>
      <li><h4><%= link_to "ログイン", login_path %></h4></li>
      <li><h4><a href="https://docs.google.com/forms/d/e/1FAIpQLSfBomBCpxTeQ-pIOlRCxRpCyJuGS9VUoYV6h-GfwTaf8V_IPw/viewform?usp=pp_url">お問い合わせ</a></h4></li>
     </div>
    <div class="pc navbar_guide">
      <li><p><%= link_to "新規登録", signup_path %></p></li>
      <li><p><%= link_to "ログイン", login_path %></p></li>
      <li><p><a href="https://docs.google.com/forms/d/e/1FAIpQLSfBomBCpxTeQ-pIOlRCxRpCyJuGS9VUoYV6h-GfwTaf8V_IPw/viewform?usp=pp_url">お問い合わせ</a></p></li>
     </div>
  <% end %>
</div>

app/views/layouts/_setumei.html.erb
<ul>
  <li>
    <h3>1</h3>
    <p>左上にあるshineというボタンを押すことで、トップページに移動することができます。</p>
  </li>
  <li>
    <h3>2</h3>
    <p>自分のページはmyshineから入ることができます。画像を投稿したい場合は、
  先にタイトル投稿し、タイトルをクリックしてタイトル画面に移動してから、画像を投稿することができます。</p>
  </li>
  <li>
    <h3>3</h3>
    <p>othershineでは、アカウントを公開設定にしているユーザを表示しています。</p>
  </li>
  <li>
    <h3>4</h3>
    <p>掲示板では好きな(タイトルを作成して頂くこともできます。)タイトルをクリックし、そのページでコメントを入力することができます。
        多くの交流を楽しんでください。</p>
  </li>
  <li>
    <h3>5</h3>
    <p>ランキングでは、公開設定にしているユーザの中で、より多く閲覧されているユーザをランキング形式で表示しています。</p>
  </li>
   <li>
    <h3>6</h3>
    <p>ユーザ詳細からいつでも公開・非公開設定が行えます。</p>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Shine</title>
    <%= csrf_meta_tags %>
    
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Permanent+Marker">
     <!-- Owl Carousel CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css">
    
    <!--<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <!-- Owl Carousel JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    

   
  </head>
  <body class="<%= controller.controller_name %>_<%= controller.action_name %>">
    <%= render "layouts/navbar" %>
    <%= render 'layouts/flash_messages' %>
    
    <%= yield %>
  </body>
</html>

app/views/myshines/_myshine.html.erb
<% myshines.each do |myshine| %>
  <div class="post_detail">
    <% time_japan = Time.now.getlocal("+09:00") %>
    <p><%= myshine.created_at.strftime("%Y年 %m月 %d日") %></p>
    <% if current_user == @user %>
      <%= link_to myshine, method: :delete do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    <% end %>
    <a class="popup" href="<%= myshine.image %>"><img src="<%= myshine.image %>"></a>
  </div>  
<% end %>

    

app/views/myshines/new.html.erb
<div class="body_cover">
    <div class="myshinenew">
      <h1>画像投稿</h1>
      <div class="topic">
        <%= form_for(@myshine) do |f| %>
          <%= f.file_field :image, class: "shinepost" %>
          <%= f.hidden_field :topic_id %>
          <%= link_to "戻る", :back, class: "btn btn-warning" %><%= f.submit "投稿", class: "btn btn-warning" %>
        <% end %>
      </div>
    </div>
</div>

app/views/settings/index.js.erb
/* global $ */

  $(".box").slideToggle();

app/views/topics/show.html.erb
<div class="body_cover">
  <div class="myshineindex">
    <div class="myshineindex_name"><%= @user.name %></div>
    <div class="myshineindex_title"><%= @topic.title %></div>
    <%= link_to "一覧へ", user_path(@user), class: "btn btn-warning" %>
    <% if current_user == @user %>
      <%= link_to "画像を投稿", new_myshine_path(topic_id: @topic.id), class: "btn btn-warning" %> <%= paginate @myshines %>
    <% else %>
      <h3><%= link_to "戻る", users_path, class: "btn btn-default" %></h3>
    <% end %>
    <div class="post">
      <%= render "myshines/myshine", myshines: @myshines %>
    </div>
  </div>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="body_cover">
    <div class="toppage">
      <div class="main">
        <%= link_to user_path(current_user) do %>
          <div class="shine"><%= image_tag ("myshine.png") %></div>
        <% end %>
        <%= link_to chats_path do %>
          <div class="word"><%= image_tag ("bulletin_board.png") %></div>
        <% end %>
        <%= link_to ranking_path do %>
          <div class="ranking"><%= image_tag ("rannking.png") %></div>
        <% end %>
        <%= link_to users_path do %>
          <div class="othershine"><%= image_tag ("othersihne.png") %></div>
          <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="body_cover">
    <div class="toppage_left pc">
      <div class="maintitle"><p>shine</p></div>
      <div class="sabtitle"><p>〜最大の努力は何色にも変化することができる〜</p></div>
      <div class="toppage_button">
        <div class="word"><p><%= link_to "新規登録", signup_path %></p></div>
        <div class="shine"><p><%= link_to "ログイン", login_path %></p></div>
      </div>
    </div>
    <div class=" pc toppage_right owl-carousel owl-theme">
      <%= image_tag "carsele9.png" %>
      <%= image_tag "carsele_manner.png" %>
      <%= image_tag "carsele.png" %>
      <%= image_tag "carsele2.png" %>
      <%= image_tag "carsele3.png" %>
      <%= image_tag "carsele4.png" %>
      <%= image_tag "carsele_manner2.png" %>
      <%= image_tag "carsele5.png" %>
      <%= image_tag "carsele6.png" %>
       <%= image_tag "carsele_manner3.png" %>
      <%= image_tag "carsele7.png" %>
      <%= image_tag "carsele8.png" %>
      <%= image_tag "carsele0.png" %>
    </div>
    <div class="toppage_right owl-carousel owl-theme sp">
      <%= image_tag "sp_carsele9.png" %>
      <%= image_tag "sp_carsele_manner.png" %>
      <%= image_tag "sp_carsele.png" %>
      <%= image_tag "sp_carsele2.png" %>
      <%= image_tag "sp_carsele3.png" %>
      <%= image_tag "sp_carsele4.png" %>
      <%= image_tag "sp_carsele_manner2.png" %>
      <%= image_tag "sp_carsele5.png" %>
      <%= image_tag "sp_carsele6.png" %>
      <%= image_tag "sp_carsele_manner3.png" %>
      <%= image_tag "sp_carsele7.png" %>
      <%= image_tag "sp_carsele8.png" %>
      <%= image_tag "sp_carsele0.png" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="body_cover">
  <div class="useredit">
    <h1>ユーザ編集</h1>
    <%= link_to "アカウント削除", @user, method: :delete, data: { confirm: "本当に削除してもよろしいですか？" }, class: "btn btn-danger" %>
    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.label :neme, "ユーザ名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :private, "非公開アカウント" %>
        <%= f.check_box :private, class: "form-control1" %>
      </div>
      <div class="form-group">
        <%= link_to "戻る", :back, class: "btn btn-default" %><%= f.submit "変更を保存する", class: "btn btn-warning" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="body_cover">
  <div class="user_index">
    <h1>othershine</h1>
    <%= link_to "戻る", root_path, class: "btn btn-default" %><%= paginate @users %>
    <div class="users_cover">
      <% @users.each do |user| %>
        <div class="users_index_other">
          <%= link_to user.name, user_path(user) %>
          <% unless user.myshines.blank? %>
            <div class="slider">
              <% user.myshines.limit(1).each do |myshine| %>
                <img src="<%= myshine.image %>">
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="body_cover">
  <div class="usernew">
    <h1>新規登録</h1>
    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class: "form-control", placeholder: "ユーザ名" %>
      </div>
      <div class="form-group">
        <%= f.email_field :email, class: "form-control", placeholder: "メールアドレス" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "パスワードの確認" %>
      </div>
      <div class="form-group">
          <%= f.label :private, "非公開アカウント" %>
          <%= f.check_box :private, class: "form-control1" %>
        </div>
      <%= f.submit "登録", class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

app/views/users/ranking.html.erb
<div class="body_cover">
  <div class="pv">
    <h1 class="pc">ランキング(アクセス数)</h1>
    <h1 class="sp">ランキング<br>(アクセス数)</h1>
    <%= link_to "戻る", :back, class: "btn btn-warning" %>
      <div class="pv_ranking">
        <% @users.each_with_index do |user, index| %>
          <h3><%= index+1 %>位 : <%= user.pv %>数：<%= link_to user.name, user_path(user) %></h3>
        <% end %>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="body_cover">
  <div class="myshineindex">
    <h1><%= @user.name %>shine</h1>
    <% unless current_user == @user %><%= link_to "othershineへ", users_path, class: "btn btn-default" %><% end %>
    <div class="user_show_topic_post">
      <% if current_user == @user %>
        <%= form_for(@topic) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <%= f.text_field :title, class: "form-control", placeholder: "タイトル入力"%>
          <%= f.submit "投稿", class: "btn btn-warning" %>
        <% end %>
      <% end %>
    </div>
    <div class="user_show_topic">
      <% @topics.each do |topic| %>
        <div class="title_box">
          <h2><%= link_to topic.title, topic_path(topic, user_id: @user.id) %>
            <% if current_user == @user %>
              <%= link_to topic, method: :delete do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>
            <% end %>
          </h2>
        </div>
      <% end %>
    </div>
  </div>
</div>
  